using System.ComponentModel;

namespace LootEditor.Model.Enums
{
    [TypeConverter(typeof(EnumDescriptionConverter))]
    public enum LongValueKey
    {
        [Description("Species")] Species = 2,
        [Description("Burden")] Burden = 5,
        [Description("Equipped Slots")] EquippedSlots = 10,
        [Description("Rare Id")] RareId = 17,
        [Description("Value")] Value = 19,
        [Description("Total Value")] TotalValue = 20,
        [Description("Skill Credits Available")] SkillCreditsAvail = 24,
        [Description("CreatureLevel")] CreatureLevel = 25,
        [Description("Restricted To Throne of Destiny")] RestrictedToToD = 26,
        [Description("Armor Level")] ArmorLevel = 28,
        [Description("Rank")] Rank = 30,
        [Description("Bonded")] Bonded = 33,
        [Description("Number of Followers")] NumberFollowers = 35,
        [Description("Unenchantable")] Unenchantable = 36,
        [Description("Lockpick Difficulty")] LockpickDifficulty = 38,
        [Description("Deaths")] Deaths = 43,
        [Description("Wand Element Damage Type")] WandElemDmgType = 45,
        [Description("Min Level Restrict")] MinLevelRestrict = 86,
        [Description("Max Level Restrict")] MaxLevelRestrict = 87,
        [Description("Lockpick Skill Bonus")] LockpickSkillBonus = 88,
        [Description("Affects Vital Id")] AffectsVitalId = 89,
        [Description("Affects Vital Amount")] AffectsVitalAmt = 90,
        [Description("Uses Total")] UsesTotal = 91,
        [Description("Uses Remaining")] UsesRemaining = 92,
        [Description("Date Of Birth")] DateOfBirth = 98,
        [Description("Workmanship")] Workmanship = 105,
        [Description("Spellcraft")] Spellcraft = 106,
        [Description("Current Mana")] CurrentMana = 107,
        [Description("Maximum Mana")] MaximumMana = 108,
        [Description("Lore Requirement")] LoreRequirement = 109,
        [Description("Rank Requirement")] RankRequirement = 110,
        [Description("Portal Restrictions")] PortalRestrictions = 111,
        [Description("Gender")] Gender = 113,
        [Description("Attuned")] Attuned = 114,
        [Description("Skill Level Required")] SkillLevelReq = 115,
        [Description("Mana Cost")] ManaCost = 117,
        [Description("Age")] Age = 125,
        [Description("XP For VP Reduction")] XPForVPReduction = 129,
        [Description("Material")] Material = 131,
        [Description("Wield Req Type")] WieldReqType = 158,
        [Description("Wield Req Attribute")] WieldReqAttribute = 159,
        [Description("Wield Req Value")] WieldReqValue = 160,
        [Description("Slayer Species")] SlayerSpecies = 166,
        [Description("Cooldown Seconds")] CooldownSeconds = 167,
        [Description("Number Items Salvaged From")] NumberItemsSalvagedFrom = 170,
        [Description("Number Times Tinkered")] NumberTimesTinkered = 171,
        [Description("Description Format")] DescriptionFormat = 172,
        [Description("Pages Used")] PagesUsed = 174,
        [Description("Pages Total")] PagesTotal = 175,
        [Description("Activation Req Skill Id")] ActivationReqSkillId = 176,
        [Description("Gem Setting Qty")] GemSettingQty = 177,
        [Description("Gem Setting Type")] GemSettingType = 178,
        [Description("Imbued")] Imbued = 179,
        [Description("Heritage")] Heritage = 188,
        [Description("Fishing Skill")] FishingSkill = 192,
        [Description("Keys Held")] KeysHeld = 193,
        [Description("Elemental Damage Bonus")] ElementalDmgBonus = 204,

        [Description("Armor Set ID")] ArmorSetID = 265,

        [Description("Item Max Level")] ItemMaxLevel = 319,
        [Description("Cloak Chance Type")] CloakChanceType = 352,
        [Description("Weapon Mastery Category")] WeaponMasteryCategory = 353,

        [Description("Summoning Gem Buffed Skill Req")] SummoningGemBuffedSkillReq = 367,
        [Description("Summoning Gem Level Req")] SummoningGemLevelReq = 369,

        [Description("Damage Rating")] DamRating = 370,
        [Description("Damage Resist Rating")] DamResistRating = 371,
        [Description("Crit Rating")] CritRating = 372,
        [Description("Crit Resist Rating")] CritResistRating = 373,
        [Description("Crit Damage Rating")] CritDamRating = 374,
        [Description("Crit Damage Resist Rating")] CritDamResistRating = 375,

        [Description("Heal Boost Rating")] HealBoostRating = 376,
        [Description("Vitality Rating")] VitalityRating = 379,

        [Description("Type")] Type = 218103808,
        [Description("Icon")] Icon = 218103809,
        [Description("Container")] Container = 218103810,
        [Description("Landblock")] Landblock = 218103811,
        [Description("Item Slots")] ItemSlots = 218103812,
        [Description("Pack Slots")] PackSlots = 218103813,
        [Description("Stack Count")] StackCount = 218103814,
        [Description("Stack Max")] StackMax = 218103815,
        [Description("Associated Spell")] AssociatedSpell = 218103816,
        [Description("Slot")] Slot = 218103817,
        [Description("Wielder")] Wielder = 218103818,
        [Description("Wielding Slot")] WieldingSlot = 218103819,
        [Description("Monarch")] Monarch = 218103820,
        [Description("Coverage")] Coverage = 218103821,
        [Description("Equippable Slots")] EquippableSlots = 218103822,
        [Description("Equip Type")] EquipType = 218103823,
        [Description("Icon Outline")] IconOutline = 218103824,
        [Description("Missile Type")] MissileType = 218103825,
        [Description("Usage Mask")] UsageMask = 218103826,
        [Description("House Owner")] HouseOwner = 218103827,
        [Description("Hook Mask")] HookMask = 218103828,
        [Description("Hook Type")] HookType = 218103829,
        [Description("Model")] Model = 218103830,
        [Description("Flags")] Flags = 218103831,
        [Description("Create Flags 1")] CreateFlags1 = 218103832,
        [Description("Create Flags 2")] CreateFlags2 = 218103833,
        [Description("Category")] Category = 218103834,
        [Description("Behavior")] Behavior = 218103835,
        [Description("Magic Defense")] MagicDef = 218103836,
        [Description("Special Properties")] SpecialProps = 218103837,
        [Description("Spell Count")] SpellCount = 218103838,
        [Description("Weapon Speed")] WeapSpeed = 218103839,
        [Description("Equip Skill")] EquipSkill = 218103840,
        [Description("DamageType")] DamageType = 218103841,
        [Description("Max Damage")] MaxDamage = 218103842,
        [Description("Unknown10")] Unknown10 = 218103843,
        [Description("Unknown100000")] Unknown100000 = 218103844,
        [Description("Unknown800000")] Unknown800000 = 218103845,
        [Description("Unknown8000000")] Unknown8000000 = 218103846,
        [Description("Physics Data Flags")] PhysicsDataFlags = 218103847,
        [Description("Active Spell Count")] ActiveSpellCount = 218103848,
        [Description("Icon Overlay")] IconOverlay = 218103849,
        [Description("Icon Underlay")] IconUnderlay = 218103850
    }
}