using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LootEditor.Model.Enums
{
    public enum Material
    {
        [Description("Agate")] Agate = 10,
        [Description("Alabaster")] Alabaster = 66,
        [Description("Amber")] Amber = 11,
        [Description("Amethyst")] Amethyst = 12,
        [Description("Aquamarine")] Aquamarine = 13,
        [Description("Armoredillo Hide")] ArmoredilloHide = 53,
        [Description("Azurite")] Azurite = 14,
        [Description("Black Garnet")] BlackGarnet = 15,
        [Description("Black Opal")] BlackOpal = 16,
        [Description("Bloodstone")] Bloodstone = 17,
        [Description("Brass")] Brass = 57,
        [Description("Bronze")] Bronze = 58,
        [Description("Carnelian")] Carnelian = 18,
        [Description("Ceramic")] Ceramic = 1,
        [Description("Citrine")] Citrine = 19,
        [Description("Copper")] Copper = 59,
        [Description("Diamond")] Diamond = 20,
        [Description("Ebony")] Ebony = 73,
        [Description("Emerald")] Emerald = 21,
        [Description("Fire Opal")] FireOpal = 22,
        [Description("Gold")] Gold = 60,
        [Description("Granite")] Granite = 67,
        [Description("Green Garnet")] GreenGarnet = 23,
        [Description("Green Jade")] GreenJade = 24,
        [Description("Gromnie Hide")] GromnieHide = 54,
        [Description("Hematite")] Hematite = 25,
        [Description("Imperial Topaz")] ImperialTopaz = 26,
        [Description("Iron")] Iron = 61,
        [Description("Ivory")] Ivory = 51,
        [Description("Jet")] Jet = 27,
        [Description("Lapis Lazuli")] LapisLazuli = 28,
        [Description("Lavender Jade")] LavenderJade = 29,
        [Description("Leather")] Leather = 52,
        [Description("Linen")] Linen = 4,
        [Description("Mahogany")] Mahogany = 74,
        [Description("Malachite")] Malachite = 30,
        [Description("Marble")] Marble = 68,
        [Description("Moonstone")] Moonstone = 31,
        [Description("Oak")] Oak = 75,
        [Description("Obsidian")] Obsidian = 69,
        [Description("Onyx")] Onyx = 32,
        [Description("Opal")] Opal = 33,
        [Description("Peridot")] Peridot = 34,
        [Description("Pine")] Pine = 76,
        [Description("Porcelain")] Porcelain = 2,
        [Description("Pyreal")] Pyreal = 62,
        [Description("Red Garnet")] RedGarnet = 35,
        [Description("Red Jade")] RedJade = 36,
        [Description("Reed Shark Hide")] ReedSharkHide = 55,
        [Description("Rose Quartz")] RoseQuartz = 37,
        [Description("Ruby")] Ruby = 38,
        [Description("Sandstone")] Sandstone = 70,
        [Description("Sapphire")] Sapphire = 39,
        [Description("Satin")] Satin = 5,
        [Description("Serpentine")] Serpentine = 71,
        [Description("Silk")] Silk = 6,
        [Description("Silver")] Silver = 63,
        [Description("Smokey Quartz")] SmokeyQuartz = 40,
        [Description("Steel")] Steel = 64,
        [Description("Sunstone")] Sunstone = 41,
        [Description("Teak")] Teak = 77,
        [Description("Tiger Eye")] TigerEye = 42,
        [Description("Tourmaline")] Tourmaline = 43,
        [Description("Turquoise")] Turquoise = 44,
        [Description("Velvet")] Velvet = 7,
        [Description("White Jade")] WhiteJade = 45,
        [Description("White Quartz")] WhiteQuartz = 46,
        [Description("White Sapphire")] WhiteSapphire = 47,
        [Description("Wool")] Wool = 8,
        [Description("Yellow Garnet")] YellowGarnet = 48,
        [Description("Yellow Topaz")] YellowTopaz = 49,
        [Description("Zircon")] Zircon = 50

    }
}
