using System.ComponentModel;

namespace LootEditor.Models.Enums;

[TypeConverter(typeof(EnumDescriptionConverter))]
public enum ObjectClass
{
    Unknown = 0,
    [Description("Melee Weapon")] MeleeWeapon = 1,
    Armor = 2,
    Clothing = 3,
    Jewelry = 4,
    Monster = 5,
    Food = 6,
    Money = 7,
    Misc = 8,
    [Description("Missile Weapon")] MissileWeapon = 9,
    Container = 10,
    Gem = 11,
    [Description("Spell Component")] SpellComponent = 12,
    Key = 13,
    Portal = 14,
    [Description("Trade Note")] TradeNote = 15,
    [Description("Mana Stone")] ManaStone = 16,
    Plant = 17,
    [Description("Base Cooking")] BaseCooking = 18,
    [Description("Base Alchemy")] BaseAlchemy = 19,
    [Description("Base Fletching")] BaseFletching = 20,
    [Description("Crafted Cooking")] CraftedCooking = 21,
    [Description("Crafted Alchemy")] CraftedAlchemy = 22,
    [Description("Crafted Fletching")] CraftedFletching = 23,
    Player = 24,
    Vendor = 25,
    Door = 26,
    Corpse = 27,
    Lifestone = 28,
    [Description("Healing Kit")] HealingKit = 29,
    Lockpick = 30,
    [Description("Wand/Staff/Orb")] WandStaffOrb = 31,
    Bundle = 32,
    Book = 33,
    Journal = 34,
    Sign = 35,
    Housing = 36,
    [Description("NPC")] Npc = 37,
    Foci = 38,
    Salvage = 39,
    Ust = 40,
    Services = 41,
    Scroll = 42,
}